#!/bin/bash -e
#
# Run all tests

cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

export GO111MODULE=on
GO="go"
PACKAGES=$(go list ./... | grep -vE 'vendor')
FILES=$(find . -name "*.go" | grep -vE "vendor")
TOPDIRS=$(ls -d */ | grep -vE "vendor")


echo "Running tests..."
${GO} test -v -cover ${PACKAGES}

echo "Checking gofmt..."
gofmt -s -l -w ${FILES} 2>&1 | awk '{print} END{if(NR>0) {exit 1}}'

echo "Checking govet..."
${GO} tool vet -all -shadow ${TOPDIRS} 2>&1 | tee /dev/stderr | awk '/shadows declaration/{next}{count+=1} END{if(count>0) {exit 1}}'

# GO111MODULE=off go get github.com/kisielk/errcheck
# echo "errcheck"
# errcheck -blank ${PACKAGES} | grep -v "_test\.go" | awk '{print} END{if(NR>0) {exit 1}}'

GO111MODULE=off go get github.com/golang/lint/golint
echo "Checking golint..."
golint -set_exit_status ${PACKAGES}

echo "Success"
